### ISSUE TITLE
Update JQuery?

### ISSUE THREAD

**Issue by terrill** [uweb/UW-Header-Templates#3]
The files [header.html](https://github.com/uweb/UW-Header-Templates/blob/master/header.html) and [header-mini-search.html](https://github.com/uweb/UW-Header-Templates/blob/master/header-mini-search.html) are both still using JQuery 1.9.1: 

`<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js?ver=1.9.1'></script>`

Is it safe to update that? If so, what's the latest version that's been tested?

**Comment by lcaple** [comment]
The highest version of jQuery that will work out of the box is 1.12.4.

Our code had to be refactored a bit to work on jQuery 3.6.0 (which ships with WordPress) so it's not safe to update without testing and using jQuery Migrate.

**Comment by terrill** [comment]
Thanks @lcaple !
